---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/pivnet --version
    register: pivnet_test_output
  - name: pivnet --version
    debug:
      msg: '{{ pivnet_test_output.stdout }}'
